name: Job Alert Bot

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image
        run: docker pull minekirmaci/job-alert-bot:latest

      - name: Run container
        id: job-alert
        run: |
          # Container'ı çalıştır ve çıktıyı yakala
          output=$(docker run --rm \
            -e EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }} \
            -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} \
            minekirmaci/job-alert-bot:latest)
          echo "$output"

          # Environment variable olarak kaydet
          echo "STATUS=$output" >> $GITHUB_ENV

      - name: Update GitHub Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = 1; // Buraya gerçek issue numarasını yaz
            const status = process.env.STATUS; // Yeni kaydedilen env variable
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: status
            })