name: Job Alert Bot

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image
        run: docker pull minekirmaci/job-alert-bot:latest

      - name: Run container
        id: job-alert
        run: |
          output=$(docker run --rm \
            -e EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }} \
            -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} \
            minekirmaci/job-alert-bot:latest)
          echo "$output"
          echo "::set-output name=status::$output"

      - name: Update GitHub Issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = 1;
            const status = '${{ steps.job-alert.outputs.status }}';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: status
            })